import {Product} from "@/types/product/types";
import {Categories, Measures} from "@/types/product/enums";

export const mockProducts: Product[] = [
  {
    id: "",
    name: "Suplemento sumo real amargo sabor de melão",
    description: "Suplemento natural à base de melão amargo com propriedades antioxidantes e digestivas. Rico em vitaminas e minerais essenciais para o bem-estar geral. Indicado para auxiliar no metabolismo e digestão.",
    line: "Linha Oleum",
    price: 67.90,
    weight: 500,
    measure: Measures.MILLILITER,
    image_url: "/mock1.png",
    category: Categories.BEM_ESTAR,
    stock: 24,
    created_at: "",
    updated_at: ""
  },
  {
    id: "",
    name: "Gel bálsamo sucuri balsâmico musc e artic",
    description: "Gel bálsamo com extratos naturais de sucuri, almíscar e menta ártica. Proporciona alívio imediato para dores musculares e articulares. Textura refrescante e absorção rápida.",
    line: "Linha Oleum",
    price: 89.50,
    weight: 120,
    measure: Measures.GRAM,
    image_url: "/mock2.png",
    category: Categories.BEM_ESTAR,
    stock: 67,
    created_at: "",
    updated_at: ""
  },
  {
    id: "",
    name: "Creme venoxflam premium para as pernas",
    description: "Creme premium desenvolvido especialmente para cuidados das pernas. Fórmula exclusiva com ativos que promovem sensação de leveza e conforto. Ideal para uso diário em pernas cansadas.",
    line: "Linha Oleum",
    price: 124.90,
    weight: 200,
    measure: Measures.GRAM,
    image_url: "/mock3.png",
    category: Categories.COSMECEUTICOS,
    stock: 18,
    created_at: "",
    updated_at: ""
  },
  {
    id: "",
    name: "Puryam elixir de inhame e vitamina A",
    description: "Elixir concentrado enriquecido com extrato de inhame selvagem e vitamina A. Fórmula única que contribui para a saúde da pele e mucosas. Rico em antioxidantes naturais.",
    line: "Linha Oleum",
    price: 78.40,
    weight: 250,
    measure: Measures.MILLILITER,
    image_url: "/mock1.png",
    category: Categories.COSMECEUTICOS,
    stock: 43,
    created_at: "",
    updated_at: ""
  },
  {
    id: "",
    name: "Kit de higiene íntima completo com higieprocto",
    description: "Kit completo para higiene íntima feminina com fórmula suave e pH balanceado. Contém sabonete líquido, lenços umedecidos e creme hidratante. Dermatologicamente testado.",
    line: "Linha Oleum",
    price: 156.80,
    weight: 350,
    measure: Measures.GRAM,
    image_url: "/mock2.png",
    category: Categories.DERMATOLOGICOS,
    stock: 31,
    created_at: "",
    updated_at: ""
  },
  {
    id: "",
    name: "Oleum alecrim essencial para cuidados com a pele",
    description: "Óleo essencial puro de alecrim para tratamentos dermatológicos. Propriedades anti-inflamatórias e antissépticas. Ideal para peles oleosas e com tendência à acne.",
    line: "Linha Oleum",
    price: 94.20,
    weight: 30,
    measure: Measures.MILLILITER,
    image_url: "/mock3.png",
    category: Categories.DERMATOLOGICOS,
    stock: 52,
    created_at: "",
    updated_at: ""
  },
  {
    id: "",
    name: "Proteína whey isolada sabor baunilha",
    description: "Proteína whey isolada de alta qualidade com 90% de pureza. Ideal para atletas e praticantes de atividade física. Sabor baunilha cremoso, fácil digestão e absorção rápida.",
    line: "Linha Dermosqée",
    price: 189.90,
    weight: 1,
    measure: Measures.KILOGRAM,
    image_url: "/mock1.png",
    category: Categories.ESPORTES,
    stock: 15,
    created_at: "",
    updated_at: ""
  },
  {
    id: "",
    name: "Gel energético natural com cafeína",
    description: "Gel energético formulado com carboidratos de rápida absorção e cafeína natural. Perfeito para atletas de endurance. Fornece energia sustentada durante exercícios prolongados.",
    line: "Linha Dermosqée",
    price: 12.50,
    weight: 32,
    measure: Measures.GRAM,
    image_url: "/mock2.png",
    category: Categories.ESPORTES,
    stock: 89,
    created_at: "",
    updated_at: ""
  },
  {
    id: "",
    name: "Sabonete líquido antibacteriano premium",
    description: "Sabonete líquido com ação antibacteriana e hidratante. Fórmula suave enriquecida com glicerina e extratos naturais. Remove 99,9% das bactérias sem ressecar a pele.",
    line: "Linha Dermosqée",
    price: 28.90,
    weight: 500,
    measure: Measures.MILLILITER,
    image_url: "/mock3.png",
    category: Categories.HIGIENE,
    stock: 76,
    created_at: "",
    updated_at: ""
  },
  {
    id: "",
    name: "Desodorante roll-on 48h proteção intensa",
    description: "Desodorante roll-on com proteção de 48 horas contra odor e umidade. Fórmula com ativos antitranspirantes e fragrância suave. Testado dermatologicamente, não irrita a pele.",
    line: "Linha Dermosqée",
    price: 18.90,
    weight: 50,
    measure: Measures.MILLILITER,
    image_url: "/mock1.png",
    category: Categories.HIGIENE,
    stock: 35,
    created_at: "",
    updated_at: ""
  },
  {
    id: "",
    name: "Multivitamínico completo com minerais",
    description: "Suplemento multivitamínico e mineral completo com 26 nutrientes essenciais. Fórmula balanceada para suprir as necessidades nutricionais diárias. Cápsulas de fácil deglutição.",
    line: "Linha Dermosqée",
    price: 89.90,
    weight: 120,
    measure: Measures.GRAM,
    image_url: "/mock2.png",
    category: Categories.SUPLEMENTOS,
    stock: 48,
    created_at: "",
    updated_at: ""
  },
  {
    id: "",
    name: "Ômega 3 concentrado EPA/DHA 1000mg",
    description: "Suplemento de ômega 3 de alta concentração com EPA e DHA. Óleo de peixe purificado livre de metais pesados. Beneficia a saúde cardiovascular e função cerebral.",
    line: "Linha Dermosqée",
    price: 145.80,
    weight: 60,
    measure: Measures.GRAM,
    image_url: "/mock3.png",
    category: Categories.SUPLEMENTOS,
    stock: 22,
    created_at: "",
    updated_at: ""
  },
]