import {Product} from "@/types/product/types";
import {Categories, Measures} from "@/types/product/enums";

export const mockProducts: Product[] = [
  {
    id: "",
    name: "Product",
    description: "Description of Product",
    line: "Linha Oleum",
    price: 20.0,
    weight: 20,
    measure: Measures.GRAM,
    image_url: "/mock1.png",
    category: Categories.BEM_ESTAR,
    stock: 1,
    created_at: "",
    updated_at: ""
  },
  {
    id: "",
    name: "Product",
    description: "Description of Product",
    line: "Linha Oleum",
    price: 20.0,
    weight: 20,
    measure: Measures.GRAM,
    image_url: "/mock2.png",
    category: Categories.BEM_ESTAR,
    stock: 2,
    created_at: "",
    updated_at: ""
  },
  {
    id: "",
    name: "Product",
    description: "Description of Product",
    line: "Linha Oleum",
    price: 20.0,
    weight: 20,
    measure: Measures.GRAM,
    image_url: "/mock3.png",
    category: Categories.COSMECEUTICOS,
    stock: 3,
    created_at: "",
    updated_at: ""
  },
  {
    id: "",
    name: "Product",
    description: "Description of Product",
    line: "Linha Oleum",
    price: 20.0,
    weight: 20,
    measure: Measures.GRAM,
    image_url: "/mock1.png",
    category: Categories.COSMECEUTICOS,
    stock: 4,
    created_at: "",
    updated_at: ""
  },
  {
    id: "",
    name: "Product",
    description: "Description of Product",
    line: "Linha Oleum",
    price: 20.0,
    weight: 20,
    measure: Measures.GRAM,
    image_url: "/mock2.png",
    category: Categories.DERMATOLOGICOS,
    stock: 5,
    created_at: "",
    updated_at: ""
  },
  {
    id: "",
    name: "Product",
    description: "Description of Product",
    line: "Linha Oleum",
    price: 20.0,
    weight: 20,
    measure: Measures.GRAM,
    image_url: "/mock3.png",
    category: Categories.DERMATOLOGICOS,
    stock: 6,
    created_at: "",
    updated_at: ""
  },
  {
    id: "",
    name: "Product",
    description: "Description of Product",
    line: "Linha Dermosqée",
    price: 20.0,
    weight: 20,
    measure: Measures.GRAM,
    image_url: "/mock1.png",
    category: Categories.ESPORTES,
    stock: 7,
    created_at: "",
    updated_at: ""
  },
  {
    id: "",
    name: "Product",
    description: "Description of Product",
    line: "Linha Dermosqée",
    price: 20.0,
    weight: 20,
    measure: Measures.GRAM,
    image_url: "/mock2.png",
    category: Categories.ESPORTES,
    stock: 8,
    created_at: "",
    updated_at: ""
  },
  {
    id: "",
    name: "Product",
    description: "Description of Product",
    line: "Linha Dermosqée",
    price: 20.0,
    weight: 20,
    measure: Measures.GRAM,
    image_url: "/mock3.png",
    category: Categories.HIGIENE,
    stock: 9,
    created_at: "",
    updated_at: ""
  },
  {
    id: "",
    name: "Product",
    description: "Description of Product",
    line: "Linha Dermosqée",
    price: 20.0,
    weight: 20,
    measure: Measures.GRAM,
    image_url: "/mock1.png",
    category: Categories.HIGIENE,
    stock: 10,
    created_at: "",
    updated_at: ""
  },
  {
    id: "",
    name: "Product",
    description: "Description of Product",
    line: "Linha Dermosqée",
    price: 20.0,
    weight: 20,
    measure: Measures.GRAM,
    image_url: "/mock2.png",
    category: Categories.SUPLEMENTOS,
    stock: 11,
    created_at: "",
    updated_at: ""
  },
  {
    id: "",
    name: "Product",
    description: "Description of Product",
    line: "Linha Dermosqée",
    price: 20.0,
    weight: 20,
    measure: Measures.GRAM,
    image_url: "/mock3.png",
    category: Categories.SUPLEMENTOS,
    stock: 12,
    created_at: "",
    updated_at: ""
  },
]